### PR TITLE
Remove most injections, keep only minimal BNS and BBH sets

### PR DESCRIPTION
**Pull request by tdent**

### CODE REVIEW

**Comment by dethodav** [comment]
Everything looks fine, but do we want to combine the two injections-bnsstt2_inj sections for simplicity?

**Comment by josh-willis** [comment]
So, it looks to me like these changes will turn off the injection filter rejection for the BNS injections, because those are in `injfilterrejector_precessing` and  the `[sharedoptions-injfilterrejector_precessing]` section (not sure *why* they are there originally). @spxiwh am I understanding that correctly? @tdent was that your intention?

**Comment by tdent** [comment]
Sorry @josh-willis I didn't notice that BNS inj were in the precessing category.  I should not have removed the injfilterrejector_precessing parts.  No need to ask Ian.

**Comment by tdent** [comment]
@dethodav if you would like to make the change 'for simplicity' then please do it yourself, I just copied-pasted-cut from the existing standard injection ini file.

**Comment by dethodav** [comment]
Looks good, merged.

**Pull request merged**
